### ISSUE TITLE
Support for other languages and subtitles?

### ISSUE THREAD

**Issue by theDyingMountain** [b-pass/plugin.video.the-chosen#1]
First thx for the plugin! Can you add some options to change the audio and/or subtitles for other languages than english?

**Comment by b-pass** [comment]
Do you have your languages selected in kodi's "Settings > Player > Language"?  For me, in 19.5, these settings work without the plugin having to do anything more.

But it looks like there are no translations available for Season 3 yet.  But if you try Season 1 or 2, it looks to have about 8 languages available for audio and about 20 for subtitles.  I am not sure how long it takes them to do translations.

**Comment by theDyingMountain** [comment]
oh, I'm very new to kodi and didn't found these settings yet. Now it works! Thx for your explanation.
