### ISSUE TITLE
Series Episodes not in English

### ISSUE THREAD

**Issue by missjane63** [b-pass/plugin.video.the-chosen#2]
The series episodes are not in English.  The BYUtv episodes are in English but those in The Chosen addon are not

**Comment by b-pass** [comment]
Hi, which episode did you try to watch and on which kodi version?  I tried a couple just now and they are in English for me.

The addon does not have its own language settings, it uses Kodi's language settings which you can view in "Settings" > "Player" > "Language" > "Preferred Audio Language".  Can you confirm you have that set to English?  Do you have "Prefer default audio streams" checked or unchecked?  (I am not sure if the default streams setting matters in this case.)

There is also an audio options menu you can access while video is playing, but how you get to it varies by which platform and interface device (keyboard, mouse, remote, gamepad) that you're using.  If you know how to get to that, can you tell me what it says?

**Comment by missjane63** [comment]
I just checked only the first four episodes of Season One and they are not in English.  My preferred audio setting is "Media Default"

This is not something I have run into before.  Does this addon not retrieve from the same source as the BYUtv addon where they play in English with the same  audio setting "Media Default"

Changing the language to English did solve the issue but I am wondering why this addon required the change.

**Comment by b-pass** [comment]
This addon gets the video directly Angel studios, makers of the Chosen.  The byutv app (even when playing The Chosen) gets the video from BYUtv.  I think BYUtv doesn't support any alternate languages so its easy for it to not get confused.

I see that in the info I'm getting from Angel and passing to Kodi there is no default language set.  English is listed first, but I guess it seems that kodi/inputstream.adaptive does not always pick the first one.  I will look into if I can force a default to English on it before letting kodi choose.  Thanks!

**Comment by missjane63** [comment]
Thanks for the reply, I was curious why the addon was doing what it was doing.
