### ISSUE TITLE
Check the Log Error and incorrect version number

### ISSUE THREAD

**Issue by missjane63** [b-pass/plugin.video.the-chosen#6]
Getting a Check the Log Error when trying to start the addon.  Was working fine a few days ago.

Also the information screen has the version number as 0.1.0 when it should be 0.2.0

Thanks

**Comment by b-pass** [comment]
Fixed and published as 0.3.0.  Thanks for reporting!

**Comment by missjane63** [comment]
Thanks, appreciate it
