### ISSUE TITLE
Unable to open/log in The Chosen addon

### ISSUE THREAD

**Issue by missjane63** [b-pass/plugin.video.the-chosen#9]
Getting the Check the Log error when trying to open The Chosen addon.

Figured I might need to get a user/pass so I signed up, entered the user/pass in the addon and tried to start the addon.

Now getting a Login Attempt Failed Error, rechecked the user/pass several times (they work at the website)

TIA

(Win 10/Kodi 21.1/The Chosen 0.4.2)

**Comment by b-pass** [comment]
Thanks, looks like they have completely changed the API (again).  It will take a couple days to sort out....

**Comment by b-pass** [comment]
Fixed in 0.4.3, thanks for reporting!
